name: CI
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: "temurin"
        java-version: "17"
    
    - name: Add repository to git safe directories
      run: git config --global --add safe.directory $GITHUB_WORKSPACE

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Check format
      run: ./gradlew spotlessCheck

    - name: Build code
      run: ./gradlew build